src/Entity/Organisation.php
<?php

namespace App\Entity;

use App\TraitClass\EntityDateTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrganisationRepository")
 * @Vich\Uploadable
 */
class Organisation implements \Serializable
{
    use EntityDateTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200,nullable=true )
     */
    private $raison_social;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $num_entreprise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="integer")
     */
    private $limite_requete;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_bouton;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_utilisateur;


    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $logo_image;

    /**
     * @ORM\Column(type="text")
     */
    private $biographie;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\User", mappedBy="organisation")
     */
    private $user;


    /**
     * @Vich\UploadableField(mapping="organisation_images", fileNameProperty="logo_image")
     * @var File
     */
    private $imageFile;
    /**
     * @Vich\UploadableField(mapping="background_organisation_images", fileNameProperty="background_organisation")
     * @var File
     */
    private $backgroundImageFile;

    /**
     * @ORM\OneToMany(targetEntity=Annonce::class, mappedBy="organisation")
     */
    private $annonces;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\ManyToOne(targetEntity=OrganisationSecteurActivite::class)
     */
    private $secteur_activite;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $background_organisation;

    /**
     * @ORM\Column(type="text", length=255)
     */
    private $selecteur;

    /**
     * @ORM\OneToMany(targetEntity=Partenaire::class, mappedBy="organisation", orphanRemoval=true)
     */
    private $partenaires;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $typeSonorisation;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $apiLink;

    public function __construct()
    {

        $this->deleted = false;
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->deleted = false;
        $this->user = new ArrayCollection();
        $this->annonces = new ArrayCollection();
        $this->partenaires = new ArrayCollection();
        $this->nombre_utilisateur = 0;
        $this->selecteur = "document.querySelector('#ref').textContent";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaisonSocial(): ?string
    {
        return $this->raison_social;
    }

    public function setRaisonSocial(string $raison_social): self
    {
        $this->raison_social = $raison_social;

        return $this;
    }

    public function getNumEntreprise(): ?string
    {
        return $this->num_entreprise;
    }

    public function setNumEntreprise(string $num_entreprise): self
    {
        $this->num_entreprise = $num_entreprise;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getLimiteRequete(): ?int
    {
        return $this->limite_requete;
    }

    public function setLimiteRequete(int $limite_requete): self
    {
        $this->limite_requete = $limite_requete;

        return $this;
    }

    public function getTypeBouton(): ?string
    {
        return $this->type_bouton;
    }

    public function setTypeBouton(string $type_bouton): self
    {
        $this->type_bouton = $type_bouton;

        return $this;
    }


    public function getLogoImage(): ?string
    {
        return $this->logo_image;
    }

    public function setLogoImage(?string $logo_image): self
    {
        $this->logo_image = $logo_image;

        return $this;
    }

    public function getBiographie(): ?string
    {
        return $this->biographie;
    }

    public function setBiographie(string $biographie): self
    {
        $this->biographie = $biographie;

        return $this;
    }

    public function adduser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
            $user->setOrganisation($this);
        }

        return $this;
    }

    public function removeuser(User $user): self
    {
        if ($this->user->contains($user)) {
            $this->user->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getOrganisation() === $this) {
                $user->setOrganisation(null);
            }
        }

        return $this;
    }

    public function getCurrentAdmin()
    {

        $users = $this->getuser()->getValues();

        foreach ($users as $element) {
            if (true === $element->getIsOrganisationAdmin()) {
                return $element;
            }
        }
        return false;

    }

    /**
     * @return Collection|User[]
     */
    public function getuser(): Collection
    {
        return $this->user;
    }

    public function __toString()
    {
        return (string)$this->raison_social;
    }

    /**
     * @return Collection|Annonce[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    /**
     *
     */
    public function getAnnoncesTextes()
    {
        return $this->annonces->getValues();
    }

    /**
     *
     */
    public function getAnnoncesSonnorises()
    {
        return $this->annonces->filter(function (Annonce $annonce) {
            return $annonce->getEstSonorise() == true;
        })->getValues();

    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setOrganisation($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonces->removeElement($annonce)) {
            // set the owning side to null (unless already changed)
            if ($annonce->getOrganisation() === $this) {
                $annonce->setOrganisation(null);
            }
        }

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getSecteurActivite(): ?OrganisationSecteurActivite
    {
        return $this->secteur_activite;
    }

    public function setSecteurActivite(?OrganisationSecteurActivite $secteur_activite): self
    {
        $this->secteur_activite = $secteur_activite;

        return $this;
    }

    public function getBackgroundOrganisation(): ?string
    {
        return $this->background_organisation;
    }

    public function setBackgroundOrganisation(?string $background_organisation): self
    {
        $this->background_organisation = $background_organisation;

        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public
    function setImageFile(?File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    /**
     * @return File
     */
    public
    function getBackgroundImageFile(): ?File
    {
        return $this->backgroundImageFile;
    }

    /**
     * @param File $backgroundImageFile
     */
    public
    function setBackgroundImageFile(?File $backgroundImageFile = null)
    {
        if ($backgroundImageFile) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
        $this->backgroundImageFile = $backgroundImageFile;
    }

    public function getSelecteur(): ?string
    {
        return $this->selecteur;
    }

    public
    function setSelecteur(string $selecteur): self
    {
        $this->selecteur = $selecteur;

        return $this;
    }

    /**
     * String representation of object
     * @link http://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public
    function serialize()
    {
        return serialize(array(
            $this->id,
            $this->raison_social,
            // see section on salt below
            // $this->salt,
        ));
    }

    /**
     * Constructs the object
     * @link http://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public
    function unserialize($serialized)
    {
        list (
            $this->id,
            $this->raison_social,
            ) = unserialize($serialized);
    }

    /**
     * @return Collection|Partenaire[]
     */

src/Entity/Partenaire.php
<?php

namespace App\Entity;

use App\Repository\PartenaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PartenaireRepository::class)
 */
class Partenaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $designation;

    /**
     * @ORM\ManyToOne(targetEntity=Organisation::class, inversedBy="partenaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organisation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    public function getOrganisation(): ?Organisation
    {
        return $this->organisation;
    }

    public function setOrganisation(?Organisation $organisation): self
    {
        $this->organisation = $organisation;

        return $this;
    }
}

src/Form/PartenaireType.php
<?php

namespace App\Form;

use App\Entity\Partenaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartenaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->remove('reference')
            ->add('organisation')
            ->add('designation', null, [
                "attr" => [
                    "class" => "form-control form-control-lg "
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Partenaire::class,
        ]);
    }
}

src/Controller/PartenaireController.php
<?php

namespace App\Controller;

use App\Entity\Partenaire;
use App\Form\PartenaireType;
use App\Repository\PartenaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/partenaire")
 */
class PartenaireController extends AbstractController
{
    /**
     * @Route("/", name="partenaire_index", methods={"GET"})
     */
    public function index(PartenaireRepository $partenaireRepository): Response
    {
        return $this->render('partenaire/index.html.twig', [
            'partenaires' => $partenaireRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="partenaire_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $partenaire = new Partenaire();
        $form = $this->createForm(PartenaireType::class, $partenaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($partenaire);
            $entityManager->flush();
            $this->addFlash("success", "Enregistrement du partenaire " . $partenaire->getDesignation() . " réussi  ");
            return $this->redirectToRoute('partenaire_index');
        }

        return $this->render('partenaire/new.html.twig', [
            'partenaire' => $partenaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="partenaire_show", methods={"GET"})
     */
    public function show(Partenaire $partenaire): Response
    {
        return $this->render('partenaire/show.html.twig', [
            'partenaire' => $partenaire,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="partenaire_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Partenaire $partenaire): Response
    {
        $form = $this->createForm(PartenaireType::class, $partenaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash("warning", "Modification du partenaire " . $partenaire->getDesignation() . " réussi  ");
            return $this->redirectToRoute('partenaire_index');
        }

        return $this->render('partenaire/edit.html.twig', [
            'partenaire' => $partenaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="partenaire_delete", methods={"POST"})
     */
    public function delete(Request $request, Partenaire $partenaire): Response
    {
        if ($this->isCsrfTokenValid('delete' . $partenaire->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $nom = $partenaire->getDesignation();

            $entityManager->remove($partenaire);
            $entityManager->flush();
            $this->addFlash("danger", "Supression du partenaire " . $nom . " réussi  ");
        }

        return $this->redirectToRoute('partenaire_index');
    }
}

templates/partenaire/_delete_form.html.twig
<form method="post" style="display: inline-block" action="{{ path('partenaire_delete', {'id': partenaire.id}) }}" onsubmit="return confirm('Comfirmer vous la suppression?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ partenaire.id) }}">
    <button class="btn btn-danger btn-sm">Supprimer</button>
</form>

templates/partenaire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<div class="col-md-11 text-center mt-3 ">
    <button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>

</div>
{{ form_end(form) }}

templates/partenaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Partenaire{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h1>Modifier le partenaire  {{ partenaire.designation }}</h1>
                    <h6 class="card-subtitle text-muted"></h6>
                </div>
                <div class="card-body">

                    {{ include('partenaire/_form.html.twig', {'button_label': 'Modifier'}) }}


                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/partenaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Partenaire index{% endblock %}

{% block body %}
    <h1>Partenaire index</h1>


    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Partenaire</h5>
                <h6 class="card-subtitle text-muted">Retrouvez ici tous les partenaires de votre organisation</h6>

            </div>
            <div class="card-body">

                <table  class="table-striped datatables-basic table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Organisation</th>
                        <th>Designation</th>
                        <th>actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for partenaire in partenaires %}
                        <tr>
                            <td>{{ partenaire.id }}</td>
                            <td>{{ partenaire.organisation.raisonSocial }}</td>
                            <td>{{ partenaire.designation }}</td>
                            <td>
                                <a class="btn btn-info btn-sm" href="{{ path('partenaire_edit', {'id': partenaire.id}) }}">Modifier</a>
                                {{ include('partenaire/_delete_form.html.twig') }}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="3">aucun enregistrement trouvé</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/partenaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Partenaire{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h1>Créer un partenaire</h1>
                    <h6 class="card-subtitle text-muted"></h6>
                </div>
                <div class="card-body">

                    {{ include('partenaire/_form.html.twig') }}

                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/partenaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Partenaire{% endblock %}

{% block body %}
    <h1>Partenaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ partenaire.id }}</td>
            </tr>
            <tr>
                <th>Reference</th>
                <td>{{ partenaire.reference }}</td>
            </tr>
            <tr>
                <th>Designation</th>
                <td>{{ partenaire.designation }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('partenaire_index') }}">back to list</a>

    <a href="{{ path('partenaire_edit', {'id': partenaire.id}) }}">edit</a>

    {{ include('partenaire/_delete_form.html.twig') }}
{% endblock %}